//
// Generated file, do not edit! Created by nedtool 5.4 from mysterio/omnet/common/msg/MinhaMensagem.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MINHAMENSAGEM_M_H
#define __MINHAMENSAGEM_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class MinhaMensagem;
// cplusplus {{
#include "mysterio/omnet/common/msg/StatusModule.h"
#include <string>
// }}

/**
 * Class generated from <tt>mysterio/omnet/common/msg/MinhaMensagem.msg:10</tt> by nedtool.
 * <pre>
 * message MinhaMensagem extends cMessage
 * {
 *     int origem = -1;
 *     int destino = -1;
 *     StatusModule status;
 *     string titulo;
 * }
 * </pre>
 */
class INET_API MinhaMensagem : public ::omnetpp::cMessage
{
  protected:
    int origem = -1;
    int destino = -1;
    StatusModule status;
    omnetpp::opp_string titulo;

  private:
    void copy(const MinhaMensagem& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MinhaMensagem&);

  public:
    MinhaMensagem(const char *name=nullptr, short kind=0);
    MinhaMensagem(const MinhaMensagem& other);
    virtual ~MinhaMensagem();
    MinhaMensagem& operator=(const MinhaMensagem& other);
    virtual MinhaMensagem *dup() const override {return new MinhaMensagem(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getOrigem() const;
    virtual void setOrigem(int origem);
    virtual int getDestino() const;
    virtual void setDestino(int destino);
    virtual const StatusModule& getStatus() const;
    virtual StatusModule& getStatusForUpdate() { return const_cast<StatusModule&>(const_cast<MinhaMensagem*>(this)->getStatus());}
    virtual void setStatus(const StatusModule& status);
    virtual const char * getTitulo() const;
    virtual void setTitulo(const char * titulo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MinhaMensagem& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MinhaMensagem& obj) {obj.parsimUnpack(b);}

#endif // ifndef __MINHAMENSAGEM_M_H

